export const colors = {
  blood: 0xb91906,
  default: 0xff0077,
  door: 0x71331e,
  // fire: 0xffd00e,
  fire: 0xfffdcc,
  floor: 0x555555,
  goblin: 0x81a842,
  player: 0xffffff,
  potion: 0xdaa520,
  stairs: 0xaaaaaa,
  tool: 0xdaa520,
  torchUnlit: 0x71331e,
  uiStatus: 0xb478ed,
  wall: 0xaaaaaa,
  weapon: 0xdaa520,
};

export const chars = {
  default: "?",
  doorOpen: "'",
  doorClosed: "+",
  floor: "•",
  goblin: "g",
  player: "@",
  potion: "!",
  stairsDown: ">",
  stairsUp: "<",
  tool: "~",
  torch: "~",
  wall: "#",
  weapon: ")",
};

// defaultBGColor: 0x000,
// inventoryHighlight: 0xa9cce3,
// items:
// armor: 0xdaa520,
// bandage: 0xf7dc6f,
// chest: 0xdaa520,
// currency: 0xdaa520,
// multipleItems: 0xdaa520,
// log
// hudText: 0xffffff,
// healthBar: 0xb91906,
// maps
// cavernFloor: 0x71331e,
// stairsUp: 0xaaaaaa,
// stairsDown: 0xaaaaaa,
// rat: 0xf1948a,
// armor: "[",
// chest: "=",
// items
// currency: "*",
// multipleItems: "&",
// item: "~",
// rat: "r",
// cavernFloor: "•",
// stairsUp: "<",
// stairsDown: ">",
// tracks
// track: "•",
